/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "ZombieAttack",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ZombieAttack__factory>;
    getContractFactory(
      name: "ZombieFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ZombieFactory__factory>;
    getContractFactory(
      name: "KittyInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.KittyInterface__factory>;
    getContractFactory(
      name: "ZombieFeeding",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ZombieFeeding__factory>;
    getContractFactory(
      name: "ZombieHelper",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ZombieHelper__factory>;
    getContractFactory(
      name: "ZombieOwnership",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ZombieOwnership__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "ZombieAttack",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ZombieAttack>;
    getContractAt(
      name: "ZombieFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ZombieFactory>;
    getContractAt(
      name: "KittyInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.KittyInterface>;
    getContractAt(
      name: "ZombieFeeding",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ZombieFeeding>;
    getContractAt(
      name: "ZombieHelper",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ZombieHelper>;
    getContractAt(
      name: "ZombieOwnership",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ZombieOwnership>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
