/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface KittyInterfaceInterface extends utils.Interface {
  functions: {
    "getKitty(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getKitty",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getKitty", data: BytesLike): Result;

  events: {};
}

export interface KittyInterface extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: KittyInterfaceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getKitty(
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        boolean,
        boolean,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        isGestating: boolean;
        isReady: boolean;
        cooldownIndex: BigNumber;
        nextActionAt: BigNumber;
        siringWithId: BigNumber;
        birthTime: BigNumber;
        matronId: BigNumber;
        sireId: BigNumber;
        generation: BigNumber;
        genes: BigNumber;
      }
    >;
  };

  getKitty(
    _id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      boolean,
      boolean,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      isGestating: boolean;
      isReady: boolean;
      cooldownIndex: BigNumber;
      nextActionAt: BigNumber;
      siringWithId: BigNumber;
      birthTime: BigNumber;
      matronId: BigNumber;
      sireId: BigNumber;
      generation: BigNumber;
      genes: BigNumber;
    }
  >;

  callStatic: {
    getKitty(
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        boolean,
        boolean,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        isGestating: boolean;
        isReady: boolean;
        cooldownIndex: BigNumber;
        nextActionAt: BigNumber;
        siringWithId: BigNumber;
        birthTime: BigNumber;
        matronId: BigNumber;
        sireId: BigNumber;
        generation: BigNumber;
        genes: BigNumber;
      }
    >;
  };

  filters: {};

  estimateGas: {
    getKitty(_id: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getKitty(
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
